export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_SIGNED_UP = 'AUTH_SIGNED_UP'

export const SET_SNACKBAR = 'SET_SNACKBAR'

export const GET_CHALLENGES = 'GET_CHALLENGES'
export const CHALLENGE_START = 'CHALLENGE_START'
export const CHALLENGE_DATE_SET = 'CHALLENGE_DATE_SET'
export const CHALLENGE_ACCEPTED = 'CHALLENGE_ACCEPTED'
export const CHALLENGE_DECLINED = 'CHALLENGE_ACCEPTED'


